server:
  port: 7001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loveluzhong/spring-cloud-conifg
          username: loveluzhong
          password: ****
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"